$ANSIBLE_VAULT;1.1;AES256
38633363333766616430333764356532653762326337393964623930386562663532356365393136
6230656161336338353336613738366639636338336232660a316365393830306533633863666439
36653961353464376362613731383035666139396362306436323438316161396433346231373134
3864653139623964390a333237393262363839383532633938303836363165326461613138386462
30663330656337306462386235303030633663363466633637313263376535363163303634363331
38646332623864613865303234653834366162613430386466333664306134313563303532623735
61626238323131323433326638383831663135383935623730303631636463653132663565356439
34663564663134373837
