apiVersion: v1
kind: Service
metadata:
  name: airtrail-service
  labels:
    app: airtrail
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: airtrail
  ports:
    - port: 80 # External port
      targetPort: 3000 # Container port
      protocol: TCP
