apiVersion: apps/v1
kind: Deployment
metadata:
  name: airtrail-deployment
  labels:
    app: airtrail
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: airtrail
  template:
    metadata:
      labels:
        app: airtrail
    spec:
      containers:
      - name: airtrail
        image: "{{ airtrail_image }}"
        env:
        - name: DB_DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: database-db
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: database-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: database-password
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: database-url
        - name: ORIGIN
          value: "{{ origin_url }}"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        ports:
        - containerPort: 3000
